import "reflect-metadata";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <div className="w-full grid grid-cols-1 xl:grid-cols-1">
            <div className="h-24 bg-gray-300 mb-2"></div>
            <div className="bg-gray-300">
              {children}
            </div>
            <div className="h-24 bg-gray-300 mt-2"></div>
        </div>
      </body>
    </html>
  );
}
